### ISSUE TITLE
"String too big" in Cyrillic in chat

### ISSUE THREAD

**Issue by McPersson** [AbdElAziz333/Pluto#25]
If you write the maximum possible message in Cyrillic in chat, you get kicked from the server with the error "io.netty.handler.codec.EncoderException: String too big (was 512 bytes encoded, max 256)" (and similar). 

This works 100% on MineCraft version 1.19.2, Forge: 43.2.8, with pluto-mc1.19.2-0.0.9 
In the single-player game this problem does not exist. 

If you write it in English, it will be fine. On 1.18.2 version this problem did not happen. I hope for a fix to this bug.

Thank you. 

![SW](https://user-images.githubusercontent.com/50740709/232247217-eab88588-e0db-4caa-b69b-7450720e46da.jpg)

**Comment by McPersson** [comment]
By the way, if you remove the mod from the client, but leave it on the server, the message banal will not appear, but you will not drop out of the server. 

I wrote a letter in Cyrillic in the chat: ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ

This is what the server writes:

```
[15апр.2023 18:36:55.143] [Netty Epoll Server IO #7/ERROR] [net.minecraft.network.PacketEncoder/]: Error receiving packet 51
io.netty.handler.codec.EncoderException: String too big (was 512 bytes encoded, max 256)
	at net.minecraft.network.FriendlyByteBuf.m_130072_(FriendlyByteBuf.java:2049) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.chat.ChatMessageContent.m_242020_(ChatMessageContent.java:24) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.chat.SignedMessageBody.m_241161_(SignedMessageBody.java:24) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.chat.PlayerChatMessage.m_240965_(PlayerChatMessage.java:41) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.protocol.game.ClientboundPlayerChatPacket.m_5779_(ClientboundPlayerChatPacket.java:21) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:45) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.77.Final.jar%2380!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110) ~[netty-codec-4.1.77.Final.jar%2380!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at net.minecraft.network.Connection.m_243087_(Connection.java:209) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.Connection.lambda$sendPacket$8(Connection.java:198) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) [netty-transport-classes-epoll-4.1.77.Final.jar%2385!/:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[15апр.2023 18:36:55.143] [Netty Epoll Server IO #3/ERROR] [net.minecraft.network.PacketEncoder/]: Error receiving packet 51
io.netty.handler.codec.EncoderException: String too big (was 512 bytes encoded, max 256)
	at net.minecraft.network.FriendlyByteBuf.m_130072_(FriendlyByteBuf.java:2049) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.chat.ChatMessageContent.m_242020_(ChatMessageContent.java:24) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.chat.SignedMessageBody.m_241161_(SignedMessageBody.java:24) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.chat.PlayerChatMessage.m_240965_(PlayerChatMessage.java:41) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.protocol.game.ClientboundPlayerChatPacket.m_5779_(ClientboundPlayerChatPacket.java:21) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:45) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.77.Final.jar%2380!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110) ~[netty-codec-4.1.77.Final.jar%2380!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at net.minecraft.network.Connection.m_243087_(Connection.java:209) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.Connection.lambda$sendPacket$8(Connection.java:198) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) [netty-transport-classes-epoll-4.1.77.Final.jar%2385!/:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[15апр.2023 18:36:55.143] [Netty Epoll Server IO #4/ERROR] [net.minecraft.network.PacketEncoder/]: Error receiving packet 51
io.netty.handler.codec.EncoderException: String too big (was 512 bytes encoded, max 256)
	at net.minecraft.network.FriendlyByteBuf.m_130072_(FriendlyByteBuf.java:2049) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.chat.ChatMessageContent.m_242020_(ChatMessageContent.java:24) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.chat.SignedMessageBody.m_241161_(SignedMessageBody.java:24) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.chat.PlayerChatMessage.m_240965_(PlayerChatMessage.java:41) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.protocol.game.ClientboundPlayerChatPacket.m_5779_(ClientboundPlayerChatPacket.java:21) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:45) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.77.Final.jar%2380!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110) ~[netty-codec-4.1.77.Final.jar%2380!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final]
	at net.minecraft.network.Connection.m_243087_(Connection.java:209) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at net.minecraft.network.Connection.lambda$sendPacket$8(Connection.java:198) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) [netty-transport-classes-epoll-4.1.77.Final.jar%2385!/:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[15апр.2023 18:36:55.143] [Netty Epoll Server IO #7/WARN] [com.connectivity.Connectivity/]: net.minecraft.network.SkipPacketException: io.netty.handler.codec.EncoderException: String too big (was 512 bytes encoded, max 256)
[15апр.2023 18:36:55.143] [Netty Epoll Server IO #4/WARN] [com.connectivity.Connectivity/]: net.minecraft.network.SkipPacketException: io.netty.handler.codec.EncoderException: String too big (was 512 bytes encoded, max 256)
[15апр.2023 18:36:55.143] [Netty Epoll Server IO #3/WARN] [com.connectivity.Connectivity/]: net.minecraft.network.SkipPacketException: io.netty.handler.codec.EncoderException: String too big (was 512 bytes encoded, max 256)
```
