### ISSUE TITLE
Failed to process update information

### ISSUE THREAD

**Issue by GenuineJakob** [AbdElAziz333/Pluto#31]
Hi, the update check doesn't work for me.

MC: 1.19.2
Forge: 43.3
Pluto: 0.0.9

'''
[pluto] Starting version check at https://github.com/AbdElAziz333/Pluto/blob/mc1.19.2/dev/updates.json
[12:26:19] [Forge Version Check/WARN] [ne.mi.fm.VersionChecker/]: Failed to process update information
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 7 column 1 path $
        at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.9.jar%2370!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar%2370!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar%2370!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar%2370!/:?] {}
        at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:183) ~[fmlcore-1.19.2-43.3.0.jar%23408!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) [?:?] {re:mixin}
        at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:114) [fmlcore-1.19.2-43.3.0.jar%23408!/:?] {}Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 7 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.9.jar%2370!/:?] {}
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[gson-2.8.9.jar%2370!/:?] {}
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.9.jar%2370!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%2370!/:?] {}
        ... 6 more
'''

**Comment by lebaston100** [comment]
I noticed that as well, it's because the url is incorrect. It should be https://raw.githubusercontent.com/AbdElAziz333/Pluto/refs/heads/mc1.19.2/dev/updates.json but i have no idea how this whole update thing works and where it would need adjustment so i can't send a PR.
