### ISSUE TITLE
Issues with krypton

### ISSUE THREAD

**Issue by Tukyer** [AbdElAziz333/Pluto#34]
So apparently I was trying to launch a modpack with some mods added by the author, some added by me, including krypton and pluto. I tried to launch the modpack and it won't let me. When I opened the log it says something about krypto and pluto module.
Heres the log: 

> Picked up _JAVA_OPTIONS: 
2024-07-29 10:30:06,866 main WARN Advanced terminal features are not available in this environment
[10:30:07] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, chimtoqua, --version, Forge 1.19.2, --gameDir, F:\Minecraft\game\home\Forge 1.19.2, --assetsDir, F:\Minecraft\game\assets, --assetIndex, 1.19, --uuid, 411a81a4be0633dfa52bad4b909f107c, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, , --xuid, , --userType, legacy, --versionType, modified, --width, 925, --height, 530, --launchTarget, forgeclient, --fml.forgeVersion, 43.4.2, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[10:30:07] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.8 by Microsoft; OS Windows 11 arch amd64 version 10.0
[10:30:08] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/F:/Minecraft/game/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2397!/ Service=ModLauncher Env=CLIENT
[10:30:08] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file F:\Minecraft\game\libraries\net\minecraftforge\fmlcore\1.19.2-43.4.2\fmlcore-1.19.2-43.4.2.jar is missing mods.toml file
[10:30:09] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file F:\Minecraft\game\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.4.2\javafmllanguage-1.19.2-43.4.2.jar is missing mods.toml file
[10:30:09] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file F:\Minecraft\game\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.4.2\lowcodelanguage-1.19.2-43.4.2.jar is missing mods.toml file
[10:30:09] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file F:\Minecraft\game\libraries\net\minecraftforge\mclanguage\1.19.2-43.4.2\mclanguage-1.19.2-43.4.2.jar is missing mods.toml file
[10:30:09] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 9 dependencies adding them to mods collection
Exception in thread "main" java.lang.module.ResolutionException: Modules krypton and pluto export package com.velocitypowered.natives to module recipeessentials
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

**Comment by NightmareMoth** [comment]
They aren't meant to be run together. Pluto is a fork of Krypton.
